Restrictions:
  IRON_ORE:
    Skill: Mining
    Level: 15
    Actionbar: ''
    Message: ''
  GOLD_ORE:
    Skill: Mining
    Level: 30
    Actionbar: ''
    Message: ''
  DIAMOND_ORE:
    Skill: Mining
    Level: 45
    Actionbar: ''
    Message: ''
  EMERALD_ORE:
    Skill: Mining
    Level: 60
    Actionbar: ''
    Message: ''