Restrictions:
  IRON_ORE:
    Skill: Mining
    Level: 15
    Actionbar: 'You must be level 15 in Mining to mine Iron Ore!'
  GOLD_ORE:
    Skill: Mining
    Level: 30
    Message: 'You must be level 30 in Mining to mine Gold Ore!'
  DIAMOND_ORE:
    Skill: Mining
    Level: 45
    Actionbar: 'You must be level 45 in Mining to mine Diamond Ore!'
  EMERALD_ORE:
    Skill: Mining
    Level: 60
    Message: 'You must be level 15 in Mining to mine Iron Ore!'