name: mcMMOMiningRestritions
version: ${project.version}
main: net.draycia.mcmmominingrestrictions.McMMOMiningRestrictions
api-version: 1.13
depend: [mcMMO]
commands:
  mmr:
    usage: /mmr reload
    permission: mmr.reload
    description: Reloads the plugin's config